[tool.poetry]
name = "spaek-dev"
version = "0.1.0"
description = ""
authors = ["박효빈 <hyo8545@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.9"
pyspark = "^3.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
